### Links

[Python cheatseat by learnpython.io](https://www.learnpytorch.io/pytorch_cheatsheet/)

### Imports

In [1]:
import torch

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("PyTorch Version: ", torch.__version__)

PyTorch Version:  2.0.1


In [3]:
if torch.backends.mps.is_available():
    print("MPS is available")

mps_device = torch.device("mps")

MPS is available


## 00. PyTorch Fundamentals

### Tensor

In [4]:
# scaler
scaler = torch.tensor(7)
scaler

print("scaler")
print()
print(scaler.ndim)
print(scaler.item())
print(scaler.shape)

scaler

0
7
torch.Size([])


In [5]:
# vector
vector = torch.tensor([7, 6])

print("vector")
print()
print(vector)
print(vector.ndim)
print(vector.shape)

vector

tensor([7, 6])
1
torch.Size([2])


In [6]:
# MATRIX
MATRIX = torch.tensor([[7, 6],
                      [5, 4]])

print("MATRIX")
print()
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

MATRIX

tensor([[7, 6],
        [5, 4]])
2
torch.Size([2, 2])


In [7]:
TENSOR = torch.tensor([[[7, 6, 6],
                        [5, 4, 8],
                        [9, 4, 3],
                        [9, 0, 7]]])

print("TENSOR")
print()
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

print(TENSOR[0])

TENSOR

tensor([[[7, 6, 6],
         [5, 4, 8],
         [9, 4, 3],
         [9, 0, 7]]])
3
torch.Size([1, 4, 3])
tensor([[7, 6, 6],
        [5, 4, 8],
        [9, 4, 3],
        [9, 0, 7]])


#### Random Tensors

Why Random Tensors?

Random tensors are imkportant because the way many neural networks learn is that they start with tensors full of random numberes and adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers -> ...`

In [9]:
# create a random tensors of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9084, 0.6873, 0.5469, 0.1215],
        [0.1512, 0.7505, 0.7233, 0.8130],
        [0.0767, 0.4941, 0.3579, 0.5894]])

In [10]:
random_tensor.ndim

2

In [49]:
# create a random tensor with similar size to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # 3 color channels, 224 height, 224 width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#### Zeros and Ones

In [13]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### Creating Tensors in  a range

In [15]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Dealing with Tensor datatypes
<div class="alert alert-danger" role="alert">
  You can fall into one of these 3 big errors in PyTorch deeplearning
    <ul class="list-group">
      <li class="list-group-item">Tensors -> not right datatype</li>
      <li class="list-group-item">Tensors -> not right device</li>
      <li class="list-group-item">Tensors -> not right shape</li>
    </ul>
</div>

In [187]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [22]:
# convert float 32 to float 16
float_16_tensor = float_32_tensor.type(torch.half)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16


In [24]:
(float_32_tensor * float_16_tensor).dtype

torch.float32

In [25]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [26]:
(float_32_tensor * int_32_tensor).dtype

torch.float32

In [189]:
print(float_32_tensor.type(torch.float16)) # convert from 32 to 16

tensor([3., 6., 9.], dtype=torch.float16)


#### Getting Infomation from Tensor
<div class="alert alert-info" role="alert">
  <ul class="list-group">
      <li class="list-group-item">tensor.datatype</li>
      <li class="list-group-item">tensor.device</li>
      <li class="list-group-item">tensor.shape</li>
    </ul>
</div>

In [70]:
# create a tensor
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.8872, 0.9544, 0.1601, 0.1520],
        [0.9893, 0.0594, 0.1033, 0.2028],
        [0.4763, 0.2385, 0.4624, 0.3066]])

In [71]:
some_tensor.shape, some_tensor.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

In [78]:
# Find out details about some tensor
print(f"some_tensor : {some_tensor}")
print()
print(f"Datatype of some_tensor: {some_tensor.dtype}")
print()
print(f"Shape of some_tensor: {some_tensor.shape}")
print()
print(f"Device of some_tensor: {some_tensor.device}")

some_tensor : tensor([1, 3, 4])

Datatype of some_tensor: torch.int64

Shape of some_tensor: torch.Size([3])

Device of some_tensor: cpu


#### Manipulating Tensors (tensor operations)
<div class="alert alert-info" role="alert">
  <ul class="list-group">
      <li class="list-group-item">
          Addition
      </li>
      <li class="list-group-item">
          Subtraction
      </li>
      <li class="list-group-item">
          Multiplication (element-wise)
      </li>
       <li class="list-group-item">
          Division
      </li>
       <li class="list-group-item">
          Matrix Multiplication
      </li>
    </ul>
</div>

In [143]:
# create a some_tensor
some_tensor = torch.tensor(data=[1,3,4])
print(f"some_tensor: {some_tensor}")

some_tensor: tensor([1, 3, 4])


In [74]:
print(f"some_tensor : {some_tensor}")
print()
print(f"Add 10 : some_tensor + 10 = {some_tensor + 10}")
print()
print(f"Multiply tensor by 10: some_tensor * 10 = {some_tensor * 10}")
print()
print(f"Substract 10 : some_tensor - 10 = {some_tensor - 10}")

some_tensor : tensor([1, 3, 4])

Add 10 : some_tensor + 10 = tensor([11, 13, 14])

Multiply tensor by 10: some_tensor * 10 = tensor([10, 30, 40])

Substract 10 : some_tensor - 10 = tensor([-9, -7, -6])


In [75]:
# try out PyTorch in-built functions
torch.mul(some_tensor, 10)

tensor([10, 30, 40])

In [76]:
torch.add(some_tensor, 10)

tensor([11, 13, 14])

In [77]:
torch.sub(some_tensor, 10)

tensor([-9, -7, -6])

##### Matrix Multiplication

In [101]:
%%time
value=0
for i in range(len(some_tensor)):
    value += some_tensor[i] * some_tensor[i]
print(value)

tensor(26, device='mps:0')
CPU times: user 2.6 ms, sys: 2.45 ms, total: 5.05 ms
Wall time: 4.28 ms


In [118]:
%%time
torch.matmul(some_tensor, some_tensor)

CPU times: user 866 µs, sys: 654 µs, total: 1.52 ms
Wall time: 782 µs


tensor(26., device='mps:0')

In [156]:
%%time
torch.matmul(some_tensor, some_tensor)

CPU times: user 33 µs, sys: 5 µs, total: 38 µs
Wall time: 42.2 µs


tensor(26)

<div class="alert alert-danger" role="alert">
  One of the most common errors in deep learning: <b>shape errors</b>
</div>

1. The **inner dimensions** must match
- `(3,2) @ (3,2)` wont work
- `(3,2) @ (2,3)` will work
- `(2,3) @ (3,2)` will work

2. The resulting matrix has the shape of the **outer dimensions**
- `(3,2) @ (2,3)` -> `(3,3)`
- `(2,3) @ (3,2)` -> `(2,2)`

In [158]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [161]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[1.2512, 0.9629, 0.3346],
        [0.5715, 0.3169, 0.1083],
        [0.7648, 0.6169, 0.2148]])

In [162]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.5000, 0.6674],
        [0.4664, 0.5442]])

In [165]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,7]])
tensor_B = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])

In [167]:
torch.mm(tensor_A, tensor_B) 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

**Showing error because the inner dimensiona are not equal betwen A and B**
<div class="alert alert-info" role="alert">
    We can fix it by using <b>Transpose</b> of the Matrix with 
    <b>tensor_A.T</b> or
    <b>tensor_B.T</b>
    <p><b>Transpose</b> switches the dimensions/axes of the tensor.</p>
</div>

In [177]:
print(f"tensor_A: \n {tensor_A}")
print()
print(f"Transpose of tensor_A: \n{tensor_A.T} \nsame elements as A but rearranged")

tensor_A: 
 tensor([[1, 2],
        [3, 4],
        [5, 7]])

Transpose of tensor_A: 
tensor([[1, 3, 5],
        [2, 4, 7]]) 
same elements as A but rearranged


In [168]:
torch.mm(tensor_A, tensor_B.T) 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 91, 115, 139]])

In [169]:
tensor_A.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

#### Tensor Aggregation (min, max, mean...)

<div class="alert alert-info" role="alert">
   Finding min, max, mean, and sum of tensors
</div>

In [15]:
# create a tensor
x = torch.arange(0,100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [5]:
print("Min:")
print(torch.min(x), x.min())
print()
print("Max:")
print(torch.max(x), x.max())

Min:
tensor(0) tensor(0)

Max:
tensor(90) tensor(90)


In [13]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [11]:
x.dtype

torch.int64

In [14]:
torch.mean(x.type(torch.float32)) # converting x to float32 and finding the mean

tensor(45.)

#### Positional Min and Max

<div class="alert alert-info" role="alert">
   Finding argmax, argmin
    <div>
        Which index does a max occur and which index does a min occur
    </div>
</div>

In [18]:
x = [7,9,0,5,3,4,7,23,4,5]
x = torch.tensor(x, dtype=torch.int32)
x, x.dtype

(tensor([ 7,  9,  0,  5,  3,  4,  7, 23,  4,  5], dtype=torch.int32),
 torch.int32)

In [19]:
x.argmin() # returns the index in the list x where minimum value occurs

tensor(2)

In [21]:
x.argmax() # returns the index in the list x where maximum value occurs

tensor(7)

#### Reshaping, viewing, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tnsor to a defined shape
* View - Return a view of an input tensor of certain shape but keeps the **same memory** as the **original tensor**
* stack - comine multiple tensorf on top of each other **(vstack)** or side by side **(hstack)**
* squeeze - removes all `1` dimensions from a tensor
* unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimension permuted (swapped) in a certain way

**Main point of all these operations is to change the shape of the tensor**

In [56]:
# let's create a tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
# adding and extra dimension
x_reshaped = x.reshape(1,9) # horizontal reshaping to 1x9
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
X_reshaped = x.reshape(9,1) # vertical reshaping to 9x1
X_reshaped, X_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [78]:
x.reshape(3,3) # worked because 3x3 = 9, 9 is number of items in x

tensor([[1234.,    5.,    3.],
        [   4.,    5.,    6.],
        [   7.,    8.,    9.]])

In [79]:
x.reshape(3,1) # didn't work because 3x1 = 3, but 9 is number of items in x

RuntimeError: shape '[3, 1]' is invalid for input of size 9

In [75]:
# change the view
z = x.view(1,9)
print(z, z.shape)

tensor([[1., 5., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


Changing z changes x as well, because **view** of a tensor **shares** the **same memory** as the **original tensor**

In [77]:
z[:, 0] = 1234
z,x

(tensor([[1234.,    5.,    3.,    4.,    5.,    6.,    7.,    8.,    9.]]),
 tensor([1234.,    5.,    3.,    4.,    5.,    6.,    7.,    8.,    9.]))

In [80]:
x.view(3,3)

tensor([[1234.,    5.,    3.],
        [   4.,    5.,    6.],
        [   7.,    8.,    9.]])

In [81]:
x.view(3,1)

RuntimeError: shape '[3, 1]' is invalid for input of size 9

In [88]:
# stack tensors on top of each other

# dim 1  = rowise - vertial
print(torch.stack([x,x], dim=1))
print()
print(torch.stack([x,x], dim=0))


# dim 0 = column wise - horizontal

tensor([[1234., 1234.],
        [   5.,    5.],
        [   3.,    3.],
        [   4.,    4.],
        [   5.,    5.],
        [   6.,    6.],
        [   7.,    7.],
        [   8.,    8.],
        [   9.,    9.]])

tensor([[1234.,    5.,    3.,    4.,    5.,    6.,    7.,    8.,    9.],
        [1234.,    5.,    3.,    4.,    5.,    6.,    7.,    8.,    9.]])


In [99]:
torch.vstack([x,x]), torch.vstack([x,x]).shape

(tensor([[1234.,    5.,    3.,    4.,    5.,    6.,    7.,    8.,    9.],
         [1234.,    5.,    3.,    4.,    5.,    6.,    7.,    8.,    9.]]),
 torch.Size([2, 9]))

In [98]:
torch.hstack([x,x]), torch.hstack([x,x]).shape


(tensor([1234.,    5.,    3.,    4.,    5.,    6.,    7.,    8.,    9., 1234.,
            5.,    3.,    4.,    5.,    6.,    7.,    8.,    9.]),
 torch.Size([18]))

In [104]:
torch.stack([x,x], dim=1)

tensor([[1234., 1234.],
        [   5.,    5.],
        [   3.,    3.],
        [   4.,    4.],
        [   5.,    5.],
        [   6.,    6.],
        [   7.,    7.],
        [   8.,    8.],
        [   9.,    9.]])

In [128]:
x = torch.zeros(9, 1,8)
x, x.shape

(tensor([[[0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0.]]]),
 torch.Size([9, 1, 8]))

In [129]:
x

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.]]])

In [133]:
x_squeezed = x.squeeze()

x_squeezed, x_squeezed.shape

(tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]),
 torch.Size([9, 8]))

` torch.Size([9, 1, 8])) ->  torch.Size([9, 8]))`
- Removed all 1 dimensions

In [138]:
x_squeezed.unsqueeze(dim=1).shape

torch.Size([9, 1, 8])

- added 1 dimension vertically

In [141]:
# permute - rearranges the dimensions of a target tensor in a specified order

# oftentimes we use this to work with images
x_original = torch.rand(size=(224,224,3)) # height, width, color channels

# permute the original tensor to trearrange the axis (or dim) to different order
x_permutted = x_original.permute(2,0,1) # 0->1, 1->2, 2->0

print(f"Original shape: {x_original.shape}")
print(f"Permuted shape: {x_permutted.shape}")


Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


#### Selecting data from tensors (**indexing**)

In [144]:
# create a new tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [170]:
print(x[0][0][0])
print(x[0,0,0])

tensor(1)
tensor(1)


In [187]:
# you can also use ":" to select "all" of a target dimension
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [188]:
# get all the values of 0th and 1st dimension but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [182]:
x[:,0,:] # -> row wise value

tensor([[1, 2, 3]])

In [216]:
x[:,:,0] # -> columnwise value

tensor([[1, 4, 7]])

In [186]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension

x[0,0,:], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [212]:
# index on x to return 9
print(x[0][2][2])
print(x[0, 2, 2])

# index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor(9)
tensor([[3, 6, 9]])


In [224]:
x[0,0,0]

tensor(1)

#### PyTorch and Numpy

- We can convert the pytorch tensor and numpy array seamlessly with each other.

In [234]:
# Numpy to Tensor
n_array = np.arange(0.0,11.0)

# convert from numpy array to torch tensor using torch.from_numpy method
t_tensor = torch.from_numpy(n_array)
n_array, n_array.dtype, t_tensor, t_tensor.dtype

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 dtype('float64'),
 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        dtype=torch.float64),
 torch.float64)

dtype is `float64` because default numpy type is `float64`

In [227]:
# Tensor to Numpy

x_tensor = torch.ones(7)

#convert from torch tensor to numpy array using .numpy() method
numpy_tensor = x_tensor.numpy()
x_tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

dtype is `float32` because default torch type is `torch.float32`

In [228]:
x_tensor = torch.ones(7, dtype=torch.int32) # changing the default datatype
numpy_tensor = x_tensor.numpy()
x_tensor, numpy_tensor

(tensor([1, 1, 1, 1, 1, 1, 1], dtype=torch.int32),
 array([1, 1, 1, 1, 1, 1, 1], dtype=int32))

- `t_tensor` and `n_array` do not share a same memory
- so changing one `will not change` the value of another

In [236]:
t_tensor = t_tensor + 1

t_tensor, n_array

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        dtype=torch.float64),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [237]:
t_tensor == n_array

False

for more on pytorch and numpy
 - https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

### PyTorch Reproducibility

Making random number reproducible


In [2]:
rand_A = torch.rand(3,4)
rand_B = torch.rand(3,4)
rand_A == rand_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

**Lets make some random but reproducible tensors**

In [12]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3,4)

print(random_C)
print(random_D)

print(random_C == random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Different ways of accessing a GPU in PyTorch

1. Google Colab
2. Use your own
3. use cloud computing platforms like GCP, AWS, Azure

In [16]:
torch.cuda.is_available()

False

#### Setting up device agnostic code
'cuda', 'cpu', 'mps'

In [23]:
# device agnostic code
device = ''
if torch.cuda.is_available():
    device = 'cuda'
elif torch.backends.mps.is_available():
    device = 'mps' 
else:
    device = 'cpu'

print("Device available: ", device)

Device available:  mps


For PyTorch, since it is capable of running in GPU or CPU, its best to setup device agnostic code

eg. run on GPU if available or CPU

#### Running it on GPU
Putting tensors/models on the GPU

Reason: GPU results in faster computations.

In [49]:
tensor_A = torch.tensor([3,4,5])
tensor_A, tensor_A.device

(tensor([3, 4, 5]), device(type='cpu'))

<div class='alert alert-info'>
    Move <b> tensor_A </b> to GPU using <b>tensor_A.to(device=device)</b> method.
</div>

In [50]:
tensor_A_gpu = tensor_A.to(device=device) # moving the tensor to gpu
tensor_A_gpu, tensor_A.device

(tensor([3, 4, 5], device='mps:0'), device(type='cpu'))

In [52]:
tensor_B = torch.tensor([3,4,5], device=device) # directly creating a tensor in gpu
tensor_B, tensor_B.device

(tensor([3, 4, 5], device='mps:0'), device(type='mps', index=0))

In [53]:
# shows error because we cannot convert to numpy while on gpu
tensor_B.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

<div class='alert alert-danger'>
    We will get error because we cannot convert to numpy while on gpu.
    <br>
    So we have to move the tensor to cpu and then convert to numpy
</div>

<div class='alert alert-info'>
    Move <b> tensor_B </b> to CPU using <b>tensor_B.cpu()</b> method.
</div>

In [54]:
tensor_B_cpu = tensor_B.cpu() # taking the tensor back to cpu
tensor_B_cpu.numpy()

array([3, 4, 5])