# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.3983, 0.7609, 0.4406, 0.2495, 0.4966, 0.6615, 0.1101],
        [0.0942, 0.0502, 0.0670, 0.4522, 0.0880, 0.6741, 0.3295],
        [0.0383, 0.3500, 0.4702, 0.1837, 0.7520, 0.6079, 0.8660],
        [0.9487, 0.9646, 0.4131, 0.6610, 0.4392, 0.6716, 0.2371],
        [0.8553, 0.8313, 0.2359, 0.8144, 0.8709, 0.5371, 0.9202],
        [0.6863, 0.5862, 0.1405, 0.2333, 0.8050, 0.3534, 0.1734],
        [0.5523, 0.3243, 0.3988, 0.4506, 0.6306, 0.6414, 0.7097]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [10]:
# Create another random tensor
tensor_A = torch.rand(size=(1,7))
# Perform matrix multiplication 
print(f"{tensor} \n@\n{tensor_A.T}: ")
print(tensor @ tensor_A.T)

tensor([[0.3983, 0.7609, 0.4406, 0.2495, 0.4966, 0.6615, 0.1101],
        [0.0942, 0.0502, 0.0670, 0.4522, 0.0880, 0.6741, 0.3295],
        [0.0383, 0.3500, 0.4702, 0.1837, 0.7520, 0.6079, 0.8660],
        [0.9487, 0.9646, 0.4131, 0.6610, 0.4392, 0.6716, 0.2371],
        [0.8553, 0.8313, 0.2359, 0.8144, 0.8709, 0.5371, 0.9202],
        [0.6863, 0.5862, 0.1405, 0.2333, 0.8050, 0.3534, 0.1734],
        [0.5523, 0.3243, 0.3988, 0.4506, 0.6306, 0.6414, 0.7097]]) 
@
tensor([[0.6870],
        [0.8358],
        [0.3961],
        [0.8883],
        [0.4791],
        [0.5968],
        [0.2928]]): 
tensor([[1.9706],
        [1.0758],
        [1.6449],
        [2.8894],
        [3.1065],
        [1.8717],
        [2.1014]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [20]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_A = torch.rand(7,7)
tensor_B = torch.rand(1,7)


# Matrix multiply tensors
output = torch.matmul(tensor_A, tensor_B.T)
output, output.size()

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [21]:
# Set random seed on the GPU
torch.mps.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [45]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = 'cuda'
# elif torch.backends.mps.is_available():
#     device='mps'
else:
    device='cpu'

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3), device=device)
tensor_B = torch.rand(size=(2,3), device=device)

print(f"Device: {device}")

print(tensor_A)
print(tensor_B)


Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [46]:
# Perform matmul on tensor_A and tensor_B
matmul = torch.matmul(tensor_A, tensor_B.T)
matmul, matmul.size()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [47]:
# Find max
print(matmul.max())
# Find min
print(matmul.min())

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [48]:
# Find arg max
print(torch.argmax(matmul))

# Find arg min
print(torch.argmin(matmul))

tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [51]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_s = tensor.squeeze()

# Print out tensors and their shapes
tensor_s, tensor_s.size()

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

In [55]:
tensor_s.unsqueeze(dim=0)

tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]])